# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "virtio_scsi"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # enable DHCP to get an IPv4 address
  networking.interfaces.enp1s0.useDHCP = true;

  # IPv6!! :3
  networking.interfaces.enp1s0.ipv6.addresses = [
    {
      address = "2a01:4f8:1c1b:c957::1";
      prefixLength = 64;
    }
  ];
  networking.defaultGateway6 = {
    address = "fe80::1";
    interface = "enp1s0";
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
